package com.bpm.angular.multi_instance_hashmap;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Product implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String productCat;
   private java.lang.String productName;

   public Product()
   {
   }

   public java.lang.String getProductCat()
   {
      return this.productCat;
   }

   public void setProductCat(java.lang.String productCat)
   {
      this.productCat = productCat;
   }

   public java.lang.String getProductName()
   {
      return this.productName;
   }

   public void setProductName(java.lang.String productName)
   {
      this.productName = productName;
   }

   public Product(java.lang.String productCat, java.lang.String productName)
   {
      this.productCat = productCat;
      this.productName = productName;
   }

}